apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplehttp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: samplehttp
  template:
    metadata:
      labels:
        app: samplehttp
    spec:
      containers:
      - name: samplehttp
        image: jpalaparthi/samplehttp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50059
---
apiVersion: v1
kind: Service
metadata:
  name: samplehttp
spec:
  type: LoadBalancer
  selector:
    app: samplehttp
  ports:
  - port: 8081
    targetPort: 50059